// Copyright 2024-2025 cyxae (@cyxae)
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#define QUICK_TAP_TERM_PER_KEY

#define TAPPING_TERM 200

#define FLOW_TAP_TERM 150

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define COMBO_TERM 30

// #define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
